services:
  app:
    build: .
    container_name: conveyor-app
    ports:
      - "1200:1200"
    env_file:
      - .env
    environment:
      PGHOST: ""
      PGDATABASE: ""
      PGUSER: ""
      PGPASSWORD: ""
      PGSSL: "true"
      EMQX_ENABLED: "true"
      EMQX_URL: mqtts://k12aa2fa.ala.us-east-1.emqxsl.com:8883
      EMQX_WS_URL: wss://k12aa2fa.ala.us-east-1.emqxsl.com:8084/mqtt
      EMQX_USERNAME: admin
      EMQX_PASSWORD: admin9988
      EMQX_ORDERS_PROGRESS_TOPIC: pedidos/avances
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "npm run migrate && npm start"
