services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: conveyor-api
    ports:
      - "1200:1200"
    env_file:
      - .env
    environment:
      PGHOST: ""
      PGDATABASE: ""
      PGUSER: ""
      PGPASSWORD: ""
      PGSSL: "true"
      EMQX_ENABLED: "true"
      EMQX_URL: mqtts://k12aa2fa.ala.us-east-1.emqxsl.com:8883
      EMQX_WS_URL: wss://k12aa2fa.ala.us-east-1.emqxsl.com:8084/mqtt
      EMQX_USERNAME: admin
      EMQX_PASSWORD: admin9988
      EMQX_ORDERS_PROGRESS_TOPIC: pedidos/avances
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "npm run migrate && npm start"

  emulator:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    container_name: conveyor-emulator
    env_file:
      - .env
    environment:
      MQTT_BROKER: k12aa2fa.ala.us-east-1.emqxsl.com
      MQTT_PORT: "8883"
      MQTT_TLS: "true"
      MQTT_USERNAME: admin
      MQTT_PASSWORD: admin9988
      SIM_UI_HOST: 0.0.0.0
      SIM_UI_PORT: "5055"
      SIM_API_BASE_URL: http://api:1200/api/v1
    ports:
      - "5055:5055"
